/**
 * Mock MOQ and pricing data for the Help Center pricing calculator.
 * Structure simulates a future database-backed model (e.g. product + pricing tables).
 */

export interface MockPricingTier {
  code: 'basic' | 'advanced' | 'exclusive'
  label: string
  multiplier: number
}

export interface MockProductPricingRecord {
  id: string
  slug: string
  productName: string
  category: string
  unit: string
  minimumOrderQuantity: number
  baseUnitPrice: number
  currency: 'USD'
  pricingTiers: MockPricingTier[]
  isActive: boolean
}

const DEFAULT_TIERS: MockPricingTier[] = [
  { code: 'basic', label: 'Basic', multiplier: 1 },
  { code: 'advanced', label: 'Advanced', multiplier: 1.15 },
  { code: 'exclusive', label: 'Exclusive', multiplier: 1.35 },
]

export const MOCK_PRODUCT_PRICING_RECORDS: MockProductPricingRecord[] = [
  {
    id: 'folding-carton-boxes',
    slug: 'folding-carton-boxes',
    productName: 'Folding Carton Boxes',
    category: 'boxes',
    unit: 'boxes',
    minimumOrderQuantity: 1000,
    baseUnitPrice: 0.85,
    currency: 'USD',
    pricingTiers: DEFAULT_TIERS,
    isActive: true,
  },
  {
    id: 'corrugated-boxes',
    slug: 'corrugated-boxes',
    productName: 'Corrugated Boxes',
    category: 'boxes',
    unit: 'boxes',
    minimumOrderQuantity: 500,
    baseUnitPrice: 1.2,
    currency: 'USD',
    pricingTiers: DEFAULT_TIERS,
    isActive: true,
  },
  {
    id: 'rigid-boxes',
    slug: 'rigid-boxes',
    productName: 'Rigid Boxes',
    category: 'boxes',
    unit: 'boxes',
    minimumOrderQuantity: 500,
    baseUnitPrice: 2.5,
    currency: 'USD',
    pricingTiers: DEFAULT_TIERS,
    isActive: true,
  },
  {
    id: 'paper-bags',
    slug: 'paper-bags',
    productName: 'Paper Bags',
    category: 'bags',
    unit: 'bags',
    minimumOrderQuantity: 1000,
    baseUnitPrice: 0.35,
    currency: 'USD',
    pricingTiers: DEFAULT_TIERS,
    isActive: true,
  },
  {
    id: 'gusset-bags',
    slug: 'gusset-bags',
    productName: 'Gusset Bags',
    category: 'bags',
    unit: 'bags',
    minimumOrderQuantity: 10000,
    baseUnitPrice: 0.12,
    currency: 'USD',
    pricingTiers: DEFAULT_TIERS,
    isActive: true,
  },
  {
    id: 'stand-up-pouches',
    slug: 'stand-up-pouches',
    productName: 'Stand-up Pouches',
    category: 'pouches',
    unit: 'pouches',
    minimumOrderQuantity: 10000,
    baseUnitPrice: 0.28,
    currency: 'USD',
    pricingTiers: DEFAULT_TIERS,
    isActive: true,
  },
  {
    id: 'kraft-pouches',
    slug: 'kraft-pouches',
    productName: 'Kraft Pouches',
    category: 'pouches',
    unit: 'pouches',
    minimumOrderQuantity: 10000,
    baseUnitPrice: 0.18,
    currency: 'USD',
    pricingTiers: DEFAULT_TIERS,
    isActive: true,
  },
  {
    id: 'floor-displays',
    slug: 'floor-displays',
    productName: 'Floor Displays',
    category: 'displays',
    unit: 'displays',
    minimumOrderQuantity: 100,
    baseUnitPrice: 12,
    currency: 'USD',
    pricingTiers: DEFAULT_TIERS,
    isActive: true,
  },
  {
    id: 'cardboard-inserts',
    slug: 'cardboard-inserts',
    productName: 'Cardboard Inserts',
    category: 'inserts',
    unit: 'inserts',
    minimumOrderQuantity: 1000,
    baseUnitPrice: 0.22,
    currency: 'USD',
    pricingTiers: DEFAULT_TIERS,
    isActive: true,
  },
  {
    id: 'molded-pulp-inserts',
    slug: 'molded-pulp-inserts',
    productName: 'Molded Pulp Inserts',
    category: 'inserts',
    unit: 'inserts',
    minimumOrderQuantity: 10000,
    baseUnitPrice: 0.08,
    currency: 'USD',
    pricingTiers: DEFAULT_TIERS,
    isActive: true,
  },
  {
    id: 'food-grade-paper-inserts',
    slug: 'food-grade-paper-inserts',
    productName: 'Food Grade Paper Inserts',
    category: 'inserts',
    unit: 'inserts',
    minimumOrderQuantity: 5000,
    baseUnitPrice: 0.15,
    currency: 'USD',
    pricingTiers: DEFAULT_TIERS,
    isActive: true,
  },
  {
    id: 'food-grade-boxes',
    slug: 'food-grade-boxes',
    productName: 'Food Grade Boxes',
    category: 'boxes',
    unit: 'boxes',
    minimumOrderQuantity: 5000,
    baseUnitPrice: 0.95,
    currency: 'USD',
    pricingTiers: DEFAULT_TIERS,
    isActive: true,
  },
  {
    id: 'cup-sleeves',
    slug: 'cup-sleeves',
    productName: 'Cup Sleeves',
    category: 'sleeves',
    unit: 'sleeves',
    minimumOrderQuantity: 10000,
    baseUnitPrice: 0.05,
    currency: 'USD',
    pricingTiers: DEFAULT_TIERS,
    isActive: true,
  },
  {
    id: 'labels-stickers',
    slug: 'labels-stickers',
    productName: 'Labels & Stickers',
    category: 'labels',
    unit: 'labels',
    minimumOrderQuantity: 1000,
    baseUnitPrice: 0.12,
    currency: 'USD',
    pricingTiers: DEFAULT_TIERS,
    isActive: true,
  },
  {
    id: 'kraft-paper-mailers',
    slug: 'kraft-paper-mailers',
    productName: 'Kraft Paper Mailers',
    category: 'mailers',
    unit: 'mailers',
    minimumOrderQuantity: 10000,
    baseUnitPrice: 0.35,
    currency: 'USD',
    pricingTiers: DEFAULT_TIERS,
    isActive: true,
  },
  {
    id: 'poly-mailers',
    slug: 'poly-mailers',
    productName: 'Poly Mailers',
    category: 'mailers',
    unit: 'mailers',
    minimumOrderQuantity: 10000,
    baseUnitPrice: 0.25,
    currency: 'USD',
    pricingTiers: DEFAULT_TIERS,
    isActive: true,
  },
  {
    id: 'recycled-bubble-mailers',
    slug: 'recycled-bubble-mailers',
    productName: 'Recycled Bubble Mailers',
    category: 'mailers',
    unit: 'mailers',
    minimumOrderQuantity: 10000,
    baseUnitPrice: 0.55,
    currency: 'USD',
    pricingTiers: DEFAULT_TIERS,
    isActive: true,
  },
  {
    id: 'bubble-mailers',
    slug: 'bubble-mailers',
    productName: 'Bubble Mailers',
    category: 'mailers',
    unit: 'mailers',
    minimumOrderQuantity: 10000,
    baseUnitPrice: 0.48,
    currency: 'USD',
    pricingTiers: DEFAULT_TIERS,
    isActive: true,
  },
  {
    id: 'packing-tape',
    slug: 'packing-tape',
    productName: 'Packing Tape',
    category: 'supplies',
    unit: 'rolls',
    minimumOrderQuantity: 500,
    baseUnitPrice: 2.2,
    currency: 'USD',
    pricingTiers: DEFAULT_TIERS,
    isActive: true,
  },
  {
    id: 'tissue-paper',
    slug: 'tissue-paper',
    productName: 'Tissue Paper',
    category: 'supplies',
    unit: 'sheets',
    minimumOrderQuantity: 10000,
    baseUnitPrice: 0.02,
    currency: 'USD',
    pricingTiers: DEFAULT_TIERS,
    isActive: true,
  },
  {
    id: 'food-grade-tissue-paper',
    slug: 'food-grade-tissue-paper',
    productName: 'Food Grade Tissue Paper',
    category: 'supplies',
    unit: 'sheets',
    minimumOrderQuantity: 10000,
    baseUnitPrice: 0.04,
    currency: 'USD',
    pricingTiers: DEFAULT_TIERS,
    isActive: true,
  },
]
